version: "3"
services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      - cluster.name=tubular
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
